#add nubia dp test file node
ccflags-y := -I$(srctree)/include/drm -I$(srctree)/techpack/display/msm -I$(srctree)/techpack/display/msm/dp
ccflags-y += -I$(srctree)/techpack/display/msm/sde
ccflags-y += -I$(srctree)/techpack/display/rotator

obj-$(CONFIG_NUBIA_HDMI_FEATURE) += nubia_dp_preference.o
