#
# Makefile for the nubia drivers.
#

obj-$(CONFIG_NUBIA_TOUCH)                         += touch/
obj-$(CONFIG_NUBIA_EC_COLOR)                      += ec_color/
obj-$(CONFIG_NUBIA_SENSORS)                       += stk3337/
obj-$(CONFIG_NUBIA_SENSORS_SENS)              	  += sensors_sensitivity/
obj-$(CONFIG_NUBIA_FINGERPRINT)                   += fingerprint/
obj-$(CONFIG_NUBIA_DP)                   	  += dp/
obj-$(CONFIG_NUBIA_BYPASS_ACL)                    += bypass_acl/
obj-$(CONFIG_PS5013)                    += ps5013/

